#!/usr/bin/env bash

# We need this extra script run ONCE on startup to initialize the
# database with per-image passwords.

export DEBIAN_FRONTEND=noninteractive

MYSQL_ROOT_PASSWORD=$(head /dev/urandom -c 512 | sha1sum | awk '// { print $1; }')

# MOTD & README
sed -i "s/{mysql_root_password}/$MYSQL_ROOT_PASSWORD/" /etc/update-motd.d/60-app-lemp
sed -i "s/{mysql_root_password}/$MYSQL_ROOT_PASSWORD/" /root/README

# Let's install MySQL
chmod 1777 /tmp
apt-get install -q -y mysql-server-5.5
update-rc.d mysql enable
mysqladmin -u root password $MYSQL_ROOT_PASSWORD

# Let's install phpmyadmin
PHPMYADMIN_PRESEED_FILE="/tmp/preseed-phpmyadmin"
cat <<EOF > $PHPMYADMIN_PRESEED_FILE
phpmyadmin phpmyadmin/app-password-confirm password
phpmyadmin phpmyadmin/dbconfig-install boolean true
phpmyadmin phpmyadmin/mysql/admin-pass password $MYSQL_ROOT_PASSWORD
phpmyadmin phpmyadmin/mysql/app-pass password
EOF
debconf-set-selections $PHPMYADMIN_PRESEED_FILE
apt-get install -q -y phpmyadmin
rm -f $PHPMYADMIN_PRESEED_FILE

# Go live
rm -rf /var/www/my_website/phpmyadmin
echo "<?php phpinfo();" > /var/www/my_website/index.php
ln -sf /usr/share/phpmyadmin /var/www/my_website/phpmyadmin

# this service is only needed on the first boot so we remove it here.
rm -f /etc/init/init-mysql.conf
rm -f /usr/local/sbin/oc-init-php-mysql
